services:
  postgres:
    image: postgres:15
    container_name: certifica-db
    restart: always
    environment:
      POSTGRES_USER: certifica7898
      POSTGRES_PASSWORD: xGS2xyoFaPZhUKaSZS9grXJpu
      POSTGRES_DB: certifica
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-certifica
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  certifica-api:
    build: .
    container_name: certifica-api
    restart: always
    env_file:
      - .env
    ports:
      - "3334:3333"
    depends_on:
      - postgres
      - redis
      - otel-collector
    networks: [appnet]

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686" # Jaeger UI
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888" # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # http gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
    links:
      - jaeger
    networks: [appnet]

volumes:
  pgdata:
  redis_data:
