version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: certifica-db
    restart: always
    environment:
      POSTGRES_USER: certifica7898
      POSTGRES_PASSWORD: xGS2xyoFaPZhUKaSZS9grXJpu
      POSTGRES_DB: certifica
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-certifica
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      # Jaeger vai ler métricas no Prometheus
      METRICS_STORAGE_TYPE: prometheus
      PROMETHEUS_SERVER_URL: http://prometheus:9091
      # Suporte ao conector de spanmetrics (nome/labels esperados)
      PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR: "true"
    ports:
      - "8081:16686" # UI
      - "14250:14250" # gRPC ingest (collector -> jaeger)
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "13133:13133" # health_check
      - "4317:4317" # OTLP gRPC (app -> collector, opcional)
      - "4318:4318" # OTLP HTTP (app -> collector)
      - "8889:8889" # Prometheus scrape (collector expõe métricas)
    depends_on:
      - jaeger
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    depends_on:
      - otel-collector
    restart: unless-stopped

  certifica-api:
    build: .
    container_name: certifica-api
    restart: always
    env_file:
      - .env
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    ports:
      - "3334:3333"
    depends_on:
      - postgres
      - redis
      - otel-collector

volumes:
  pgdata:
  redis_data:
