version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: certifica-db
    restart: always
    environment:
      POSTGRES_USER: certifica7898
      POSTGRES_PASSWORD: xGS2xyoFaPZhUKaSZS9grXJpu
      POSTGRES_DB: certifica
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-certifica
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686" # Jaeger UI
      - "14268:14268" # ingest HTTP (opcional)
      - "14250:14250" # ingest gRPC (collector -> jaeger)
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "1888:1888" # pprof
      - "13133:13133" # health_check
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "55679:55679" # zpages
    depends_on:
      - jaeger
    restart: unless-stopped

  certifica-api:
    build: .
    container_name: certifica-api
    restart: always
    env_file:
      - .env
    environment:
      # Força o endpoint HTTP do OTLP (mais simples)
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
      # Ajuste DB/Redis se você quiser manter tudo rodando só em Docker:
      # DATABASE_URL: postgresql://certifica7898:xGS2xyoFaPZhUKaSZS9grXJpu@postgres:5432/certifica
      # REDIS_HOST: redis
    ports:
      - "3334:3333"
    depends_on:
      - postgres
      - redis
      - otel-collector

volumes:
  pgdata:
  redis_data:
